version: 2

networks:
  primary:
    external:
      name: primary

services:
  web:
    image: registry.nush.app/steam-sqli:latest
    restart: always
    networks:
    - primary
    expose:
    - "8080"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.steam-sqli.rule=Host(`dsa.nush.app`)"
    - "traefik.http.routers.steam-sqli.entrypoints=http"